/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.politoinc.metadefenderautopsy;

import org.sleuthkit.autopsy.ingest.IngestModuleGlobalSettingsPanel;

/**
 *
 * @author Ian Duffy
 */
public class MetaDefenderGlobalSettingsPanel extends IngestModuleGlobalSettingsPanel {

    /**
     * Creates new form MetaDefenderGlobalSetttingsPanel
     */
    public MetaDefenderGlobalSettingsPanel() {
        initComponents();
    }

    @Override
    public void saveSettings() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
